name: Update Epic7 Catalog

on:
  workflow_dispatch: {}         # bouton "Run workflow"
  schedule:
    - cron: "0 6 * * 1"         # chaque lundi 06:00 UTC (modifiable)

permissions:
  contents: write               # IMPORTANT pour pousser le commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Scrape Epic7DB
        run: npm run scrape

      - name: Commit & push changes
        run: |
          if [[ -n "$(git status --porcelain data)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/*.json
            git commit -m "chore: refresh heroes.json & artifacts.json"
            git push
          else
            echo "No changes."
          fi
